# Generated by Django 3.2.5 on 2021-07-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200, verbose_name='product name')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='product price')),
                ('product_quantity', models.PositiveIntegerField(default=0, verbose_name='product quantity')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='', max_length=200, verbose_name='shop name')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_quantity', models.PositiveIntegerField(default=0, verbose_name='purchase quantity')),
                ('purchase_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('purchased_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.products', verbose_name='purchase product')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.shops', verbose_name='product shop'),
        ),
        migrations.CreateModel(
            name='CustomerCartElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_quantity', models.PositiveIntegerField(default=0, verbose_name='element quantity')),
                ('cart_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_market.products', verbose_name='element')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='total price')),
                ('cart_elements', models.ManyToManyField(blank=True, to='app_market.CustomerCartElement', verbose_name='products in cart')),
                ('customer_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer cart')),
            ],
        ),
    ]
